### ISSUE TITLE
ImportError: No module named builtins

### ISSUE THREAD

**Issue by redox** [algolia/docsearch-scraper#312]
```
% ./env/bin/python ./docsearch deploy:configs
Cloning into 'scraper'...
remote: Counting objects: 118, done.
remote: Compressing objects: 100% (104/104), done.
remote: Total 118 (delta 14), reused 63 (delta 5), pack-reused 0
Receiving objects: 100% (118/118), 54.52 KiB | 0 bytes/s, done.
Resolving deltas: 100% (14/14), done.
Checking connectivity... done.
Cloning into 'public'...
remote: Counting objects: 247, done.
remote: Compressing objects: 100% (246/246), done.
remote: Total 247 (delta 10), reused 52 (delta 1), pack-reused 0
Receiving objects: 100% (247/247), 74.27 KiB | 0 bytes/s, done.
Resolving deltas: 100% (10/10), done.
Checking connectivity... done.
Cloning into 'private'...
remote: Counting objects: 151, done.
remote: Compressing objects: 100% (7/7), done.
remote: Total 151 (delta 0), reused 148 (delta 0), pack-reused 0
Receiving objects: 100% (151/151), 9.65 KiB | 0 bytes/s, done.
Checking connectivity... done.
Traceback (most recent call last):
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/private/tmp/docsearch_deploy/scraper/scraper/deployer/index.py", line 6, in <module>
    from . import fetchers
  File "scraper/deployer/fetchers.py", line 5, in <module>
    from . import helpers
  File "scraper/deployer/helpers.py", line 5, in <module>
    from builtins import input
ImportError: No module named builtins
```

**Comment by redox** [comment]
Works if we activate the env with `. env/bin/activate`

**Comment by redox** [comment]
Seems to come from the python->shell script->python mess :)

**Comment by maxiloc** [comment]
Same here, I am closing this for now, let's see if that still happens after merging https://github.com/algolia/docsearch-scraper/pull/310
