### ISSUE TITLE
ImportError: No module named 'algolia_helper' (python 3)

### ISSUE THREAD

**Issue by redox** [algolia/docsearch-scraper#313]
```
% ./env3/bin/python ./docsearch deploy:configs
Traceback (most recent call last):
  File "./docsearch", line 3, in <module>
    from scraper.cli.index import run
  File "/Users/redox/dev/Algolia/documentation-scrapper/scraper/cli/index.py", line 19, in <module>
    from .commands.run_config import RunConfig
  File "/Users/redox/dev/Algolia/documentation-scrapper/scraper/cli/commands/run_config.py", line 2, in <module>
    from ...src.index import run_config
  File "/Users/redox/dev/Algolia/documentation-scrapper/scraper/src/index.py", line 7, in <module>
    from algolia_helper import AlgoliaHelper
ImportError: No module named 'algolia_helper'
```

**Comment by redox** [comment]
Works if we activate the env with `. env/bin/activate`

**Comment by redox** [comment]
Seems to come from the python->shell script->python mess :)

**Comment by maxiloc** [comment]
I am closing this for now, let's see if that still happens after merging https://github.com/algolia/docsearch-scraper/pull/310
