### ISSUE TITLE
ImportError: No module named dotenv

### ISSUE THREAD

**Issue by danielcollettepb** [algolia/docsearch-scraper#378]
I cloned the repo and ran `pip install --user -r requirements.txt`, all dependencies installed and I created the `.env` file with the application id and api key.

When I run `./docsearch` I get the following error:

```
Traceback (most recent call last):
  File "./docsearch", line 3, in <module>
    from cli.src.index import run
  File "/Users/DAN/Desktop/GIT/docsearch-scraper/cli/src/index.py", line 3, in <module>
    from dotenv import load_dotenv
ImportError: No module named dotenv
```
I tried uninstalling/reinstalling python-dotenv with no luck. Any ideas on how to fix this?

Here is a list of installed packages via `pip freeze`:

```
algoliasearch==1.13.0
asn1crypto==0.22.0
attrs==17.2.0
Automat==0.6.0
certifi==2017.7.27.1
cffi==1.11.0
chardet==3.0.4
click==6.7
constantly==15.1.0
cryptography==2.0.3
cssselect==1.0.1
enum34==1.1.6
future==0.16.0
hyperlink==17.3.1
idna==2.6
incremental==17.5.0
ipaddress==1.0.18
lxml==4.0.0
ndg-httpsclient==0.4.3
ordereddict==1.1
parsel==1.2.0
pyasn1==0.3.5
pyasn1-modules==0.1.4
pycparser==2.18
PyDispatcher==2.0.5
pyOpenSSL==17.3.0
pyperclip==1.5.27
python-dotenv==0.8.2
queuelib==1.4.2
ratelimit==1.4.1
requests==2.18.4
requests-file==1.4.2
Scrapy==1.4.0
selenium==2.53.6
service-identity==17.0.0
six==1.11.0
slacker==0.9.60
tldextract==2.1.0
Twisted==17.5.0
urllib3==1.22
w3lib==1.18.0
zope.interface==4.4.2
```

**Comment by s-pace** [comment]
👋 @danielcollettepb 

Sorry for the delay. Did you find a way to fix this ? 

Did you try [`pip install django_dotenv ` ](https://github.com/theskumar/python-dotenv/issues/6)

**Comment by danielcollettepb** [comment]
no, we are using a different approach to index page content using the API with puppeteer
