### ISSUE TITLE
Error running DocSearch without installing firefox

### ISSUE THREAD

**Issue by s-pace** [algolia/docsearch-scraper#382]
```
Traceback (most recent call last):
  File "./docsearch", line 5, in <module>
    run()
  File "/Users/<user>/docsearch/docsearch-scraper/cli/src/index.py", line 186, in run
    exit(command.run(sys.argv[2:]))
  File "/Users/<user>/docsearch/docsearch-scraper/cli/src/commands/run_config.py", line 21, in run
    return run_config(args[0])
  File "/Users/<user>/docsearch/docsearch-scraper/cli/../scraper/src/index.py", line 26, in run_config
    config = ConfigLoader(config)
  File "/Users/<user>/docsearch/docsearch-scraper/cli/../scraper/src/config/config_loader.py", line 78, in __init__
    self.driver = BrowserHandler.init(self.config_original_content, self.js_render)
  File "/Users/<user>/docsearch/docsearch-scraper/cli/../scraper/src/config/browser_handler.py", line 25, in init
    driver = webdriver.Firefox(profile)
  File "/Users/<user>/Library/Python/2.7/lib/python/site-packages/selenium/webdriver/firefox/webdriver.py", line 80, in __init__
    self.binary, timeout)
  File "/Users/<user>/Library/Python/2.7/lib/python/site-packages/selenium/webdriver/firefox/extension_connection.py", line 52, in __init__
    self.binary.launch_browser(self.profile, timeout=timeout)
  File "/Users/<user>/Library/Python/2.7/lib/python/site-packages/selenium/webdriver/firefox/firefox_binary.py", line 67, in launch_browser
    self._start_from_profile_path(self.profile.path)
  File "/Users/<user>/Library/Python/2.7/lib/python/site-packages/selenium/webdriver/firefox/firefox_binary.py", line 90, in _start_from_profile_path
    env=self._firefox_env)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```

**Comment by s-pace** [comment]
Solution: Install firefox 45.0.2. [Ref for MAC](https://ftp.mozilla.org/pub/firefox/releases/45.0.2/mac/en-GB/).
