### ISSUE TITLE
ModuleNotFoundError: No module named 'dotenv'

### ISSUE THREAD

**Issue by FeynmanZhou** [algolia/docsearch-scraper#436]
Hi Team,

I executed ` ./docsearch docker:build` by following this guide: 
https://community.algolia.com/docsearch/run-your-own.html
But I got the unexpected return as below,  how to resolve this issue?

```
$ ./docsearch docker:build
Traceback (most recent call last):
  File "./docsearch", line 3, in <module>
    from cli.src.index import run
  File "/root/docsearch-scraper/cli/src/index.py", line 3, in <module>
    from dotenv import load_dotenv
ModuleNotFoundError: No module named 'dotenv'
```

**Comment by s-pace** [comment]
Hi @FeynmanZhou 

Thank you for reaching out. Did you follow the installation step? It is required to correctly run the crawl from the image.

```
Install [pipenv](pipenv)
pipenv install
pipenv shell
```

Let us know

**Comment by FeynmanZhou** [comment]
Firstly, pipenv was already installed in my CentOS machine, 

Then I executed 


$ pipenv install
Pipfile.lock (e16df4) out of date, updating to (8eed84)…
Locking [dev-packages] dependencies…
Locking [packages] dependencies…
✘ Locking Failed!
Traceback (most recent call last):
  File "/home/linuxbrew/.linuxbrew/Cellar/pipenv/2018.11.26_1/libexec/lib/python3.7/site-packages/pipenv/resolver.py", line 126, in <module>
    main()
  File "/home/linuxbrew/.linuxbrew/Cellar/pipenv/2018.11.26_1/libexec/lib/python3.7/site-packages/pipenv/resolver.py", line 119, in main
    parsed.requirements_dir, parsed.packages)
  File "/home/linuxbrew/.linuxbrew/Cellar/pipenv/2018.11.26_1/libexec/lib/python3.7/site-packages/pipenv/resolver.py", line 85, in _main
    requirements_dir=requirements_dir,
  File "/home/linuxbrew/.linuxbrew/Cellar/pipenv/2018.11.26_1/libexec/lib/python3.7/site-packages/pipenv/resolver.py", line 69, in resolve
    req_dir=requirements_dir
  File "/home/linuxbrew/.linuxbrew/Cellar/pipenv/2018.11.26_1/libexec/lib/python3.7/site-packages/pipenv/utils.py", line 726, in resolve_deps
    req_dir=req_dir,
  File "/home/linuxbrew/.linuxbrew/Cellar/pipenv/2018.11.26_1/libexec/lib/python3.7/site-packages/pipenv/utils.py", line 480, in actually_resolve_deps
    resolved_tree = resolver.resolve()
  File "/home/linuxbrew/.linuxbrew/Cellar/pipenv/2018.11.26_1/libexec/lib/python3.7/site-packages/pipenv/utils.py", line 385, in resolve
    results = self.resolver.resolve(max_rounds=environments.PIPENV_MAX_ROUNDS)
  File "/home/linuxbrew/.linuxbrew/Cellar/pipenv/2018.11.26_1/libexec/lib/python3.7/site-packages/pipenv/utils.py", line 375, in resolver
    self.get_resolver(clear=self.clear, pre=self.pre)
  File "/home/linuxbrew/.linuxbrew/Cellar/pipenv/2018.11.26_1/libexec/lib/python3.7/site-packages/pipenv/utils.py", line 369, in get_resolver
    clear_caches=clear, prereleases=pre,
  File "/home/linuxbrew/.linuxbrew/Cellar/pipenv/2018.11.26_1/libexec/lib/python3.7/site-packages/pipenv/patched/piptools/resolver.py", line 55, in __init__
    cache = DependencyCache()  # pragma: no cover
  File "/home/linuxbrew/.linuxbrew/Cellar/pipenv/2018.11.26_1/libexec/lib/python3.7/site-packages/pipenv/patched/piptools/cache.py", line 55, in __init__
    os.makedirs(cache_dir)
  File "/home/linuxbrew/.local/share/virtualenvs/docsearch-scraper-TPB0NGce/lib64/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 13] Permission denied: '/home/linuxbrew/.cache/pip-tools'
File "/home/linuxbrew/.linuxbrew/Cellar/pipenv/2018.11.26_1/libexec/lib/python3.7/site-packages/pipenv/resolver.py", line 126, in <module>
    main()
  File "/home/linuxbrew/.linuxbrew/Cellar/pipenv/2018.11.26_1/libexec/lib/python3.7/site-packages/pipenv/resolver.py", line 119, in main
    parsed.requirements_dir, parsed.packages)
  File "/home/linuxbrew/.linuxbrew/Cellar/pipenv/2018.11.26_1/libexec/lib/python3.7/site-packages/pipenv/resolver.py", line 85, in _main
    requirements_dir=requirements_dir,
  File "/home/linuxbrew/.linuxbrew/Cellar/pipenv/2018.11.26_1/libexec/lib/python3.7/site-packages/pipenv/resolver.py", line 69, in resolve
    req_dir=requirements_dir
  File "/home/linuxbrew/.linuxbrew/Cellar/pipenv/2018.11.26_1/libexec/lib/python3.7/site-packages/pipenv/utils.py", line 726, in resolve_deps
    req_dir=req_dir,
  File "/home/linuxbrew/.linuxbrew/Cellar/pipenv/2018.11.26_1/libexec/lib/python3.7/site-packages/pipenv/utils.py", line 480, in actually_resolve_deps
    resolved_tree = resolver.resolve()
  File "/home/linuxbrew/.linuxbrew/Cellar/pipenv/2018.11.26_1/libexec/lib/python3.7/site-packages/pipenv/utils.py", line 385, in resolve
    results = self.resolver.resolve(max_rounds=environments.PIPENV_MAX_ROUNDS)
  File "/home/linuxbrew/.linuxbrew/Cellar/pipenv/2018.11.26_1/libexec/lib/python3.7/site-packages/pipenv/utils.py", line 375, in resolver
    self.get_resolver(clear=self.clear, pre=self.pre)
  File "/home/linuxbrew/.linuxbrew/Cellar/pipenv/2018.11.26_1/libexec/lib/python3.7/site-packages/pipenv/utils.py", line 369, in get_resolver
    clear_caches=clear, prereleases=pre,
  File "/home/linuxbrew/.linuxbrew/Cellar/pipenv/2018.11.26_1/libexec/lib/python3.7/site-packages/pipenv/patched/piptools/resolver.py", line 55, in __init__
    cache = DependencyCache()  # pragma: no cover
  File "/home/linuxbrew/.linuxbrew/Cellar/pipenv/2018.11.26_1/libexec/lib/python3.7/site-packages/pipenv/patched/piptools/cache.py", line 55, in __init__
    os.makedirs(cache_dir)
  File "/home/linuxbrew/.local/share/virtualenvs/docsearch-scraper-TPB0NGce/lib64/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 13] Permission denied: '/home/linuxbrew/.cache/pip-tools'

$ pipenv shell
Shell for /home/linuxbrew/.local/share/virtualenvs/docsearch-scraper-TPB0NGce already activated.
No action taken to avoid nested environments.

**Comment by FeynmanZhou** [comment]
Hi @s-pace , any suggestions regarding this scenario?  Thanks.

**Comment by s-pace** [comment]
Hi @FeynmanZhou, the issue raised is due to the permission of the user running this command (`Permission denied`). It involves your personal set up of `pipenv`.

Could you run this command from a user who has the appropriates Permission?

**Comment by s-pace** [comment]
Closing this inactive issue. Feel free to follow up and reopen it if needed @FeynmanZhou
