### ISSUE TITLE
TypeError: argument of type 'NoneType' is not iterable

### ISSUE THREAD

**Issue by christophemenager** [algolia/docsearch-scraper#551]
Hi there ! 

I am trying to run the command (I have no env file but env variables are set as global viariables in my terminal)

`docker run -it -e "CONFIG=$(cat algolia.config.json | jq -r tostring)" algolia/docsearch-scraper`

My error : 

```
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/root/src/index.py", line 119, in <module>
    run_config(environ['CONFIG'])
  File "/root/src/index.py", line 33, in run_config
    config = ConfigLoader(config)
  File "/root/src/config/config_loader.py", line 84, in __init__
    self._parse()
  File "/root/src/config/config_loader.py", line 120, in _parse
    self.selectors = SelectorsParser().parse(self.selectors)
  File "/root/src/config/selectors_parser.py", line 64, in parse
    if 'lvl0' in config_selectors:
TypeError: argument of type 'NoneType' is not iterable
```

On my mac OS 11.3 : 
![image](https://user-images.githubusercontent.com/17217868/116776326-1f193b00-aa68-11eb-924c-8b92c600e5fa.png)

**Comment by jer-k** [comment]
@christophemenager @Zenfection1412 It happens when you don't have `selectors` defined in your config file. I just ran into the same thing.
